#!/bin/sh
if [[ "$1" == "--skip-push" ]] ; then
  layouts_baseUrl=http://painkiller.arctair.com/layouts-dark ./gradlew \
    darkDeploy test switchDeployments
else
  layouts_baseUrl=http://painkiller.arctair.com/layouts-dark ./gradlew \
    clean shadowJar docker dockerPush darkDeploy test switchDeployments
fi
