#!/bin/sh
./gradlew shadowJar
docker build -t painkillergis/layouts:`scripts/versionByDepth` .
docker push painkillergis/layouts:`scripts/versionByDepth`
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: layouts
  labels:
    app: layouts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: layouts
  template:
    metadata:
      labels:
        app: layouts
    spec:
      containers:
      - name: layouts
        image: painkillergis/layouts:`scripts/versionByDepth`
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: layouts
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: layouts
EOF
echo waiting for deployment `scripts/versionByDepth` \(currently `scripts/deployedVersion`\)
until [ `scripts/versionByDepth` == `scripts/deployedVersion` ] ; do
  sleep 1
done
